### PR TITLE
Fixes line and column numbers not being sorted correctly.

### LINKED ISSUE #21: Line numbers seem sporadic?
This seems like some unintended consequence of #8.

For some context, I don't use warnings, so everything is an error for me. 

Based on the description of #8, I'd expect the line numbers to still be in order, but that's not the case. 
Something feels awry here...

Using the `1.0.0` release, this is some output I just got.

```
  src/app.js:1:16
  ✖  11:39  Missing JSX expression container around literal string                                          react/jsx-no-literals
  ✖  34:10  Unexpected trailing comma.                                                                      comma-dangle
  ✖  14:16  Missing JSX expression container around literal string                                          react/jsx-no-literals
  ✖   1:16  Component is defined but never used.                                                            no-unused-vars
  ✖   6:15  name is missing in props validation                                                             react/prop-types
  ✖  32:17  Expected object keys to be in natural insensitive ascending order. name should be before type.  sort-keys
  ✖  25:39  ownProps is defined but never used.                                                             no-unused-vars
  ✖  21:25  Unexpected trailing comma.                                                                      comma-dangle
  ✖  19:33  ownProps is defined but never used.                                                             no-unused-vars
  ✖   6:21  onClick is missing in props validation                                                          react/prop-types
  ✖   6:13  Component definition is missing display name                                                    react/display-name
  ✖  10:17  Missing JSX expression container around literal string                                          react/jsx-no-literals
  ✖   9:17  Missing JSX expression container around literal string                                          react/jsx-no-literals
```

I cannot seem to find a rhyme or reason to the line number order.

At first, I thought it was maybe grouping them by plugin, Like `eslint` first and then `eslint-plugin-react`, but  that's not the case either.

Is this what is expected? Is there some other level of "severity" I am not grasping?

FWIW, removing the pretty formatter reports things in the order I'd expect.

### PR DESCRIPTION
**Pull request by manovotny**
I'm not necessarily happy with the verboseness of the production code, but I felt anything more clever became unreadable. I am totally open to suggestions if you have them.

Regardless, this PR correctly sorts results by severity, then line number, then column number.

Before:

index_js_-_eslint-formatter-pretty_-____developer_eslint-formatter-pretty_

After:

index_js_-_eslint-formatter-pretty_-____developer_eslint-formatter-pretty_

Fixes #21

### CODE REVIEW

**Comment by manovotny** [comment]
Hrm...

Test passes locally, but it's obviously not on ci.

The visual order on ci is correct, but it's somehow calculating the indexes differently. 

Time for bed, but I'll investigate more tomorrow.

File: index.js [hunk 1]
```diff
@@ -42,14 +42,38 @@ module.exports = results => {
...
+					} else {
+						const isError = (a.fatal || a.severity === 2) && (!b.fatal || b.severity !== 2);
+
+						if (isError) {
+							return 1;
+						}
+
+						if (!isError) {
+							return -1;
+						}
```
Comment (sindresorhus) [inline index.js]: This could just be `return isError ? 1 : -1;`. Same with the other statements.

File: test/test.js [hunk 2]
```diff
@@ -25,3 +26,18 @@ test('show line numbers', t => {
...
+	const indexes = [
+		sanitized.indexOf('⚠   1:1'),
+		sanitized.indexOf('⚠  10:2'),
+		sanitized.indexOf('✖   3:1'),
+		sanitized.indexOf('✖  30:1'),
+		sanitized.indexOf('✖  40:5'),
+		sanitized.indexOf('✖  40:8')
+	];
+	console.log(output);
+	t.deepEqual(indexes, indexes.slice(0).sort());
```
Comment (sindresorhus) [inline test/test.js]: Drop the `0`.

**Comment by sindresorhus** [comment]
Tests are failing for me too locally.

File: index.js (hunk 1 above)
Comment (manovotny) [inline index.js]: Shortening them up to that will make the `return 0;` at the end unreachable, won't it?

Comment (sindresorhus) [inline index.js]: It already is unreachable. What I commented above is equivalent to what's already there, just shorter.

Comment (manovotny) [inline index.js]: You are right. 

See! I should have gone to bed instead of firing off one more reply. 😉

**Comment by manovotny** [comment]
Ok. 

All review comments should be addressed and the build is passing now.

Please let me know if you need anything else from me.

File: test/test.js [hunk 3]
```diff
@@ -25,3 +26,20 @@ test('show line numbers', t => {
...
+		sanitized.indexOf('⚠   1:1'),
+		sanitized.indexOf('⚠  10:2'),
+		sanitized.indexOf('✖   3:1'),
+		sanitized.indexOf('✖  30:1'),
+		sanitized.indexOf('✖  40:5'),
+		sanitized.indexOf('✖  40:8')
+	];
+	console.log(output);
+	t.deepEqual(indexes, indexes.slice().sort((a, b) => {
+		return a - b;
```
Comment (sindresorhus) [inline test/test.js]: This can just be an inline arrow function.

Comment (manovotny) [inline test/test.js]: You're right. Done!

**Comment by manovotny** [comment]
@sindresorhus : : 

All review comments should be address.

**Comment by sindresorhus** [comment]
Looks great. Thank you! :)
